In [11]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier

In [2]:
df = pd.read_csv("Datasets/Question2.csv")
df

,Student,Attendance,MathScore,EnglishScore,QuizScore,MissedClasses,MathSupport,EnglishSupport,AttendanceSupport
0,Aarav,72,55,58,61,1,0,1,0
1,Sita,91,86,84,88,0,0,0,0
2,Ram,68,48,52,55,4,1,1,0
3,Anisha,94,92,89,91,0,0,0,0
4,Rohan,75,60,57,63,2,0,1,0
5,Priya,88,78,81,85,1,0,0,0
6,Kiran,62,42,45,49,5,1,1,1
7,Nabin,82,70,68,72,2,0,0,0
8,Suman,70,50,54,58,3,1,1,0
9,Alisha,96,94,92,95,0,0,0,0


In [21]:
X = df[
    [
        "Attendance",
        "MathScore",
        "EnglishScore",
        "QuizScore",
        "MissedClasses",
        
    ]
]
y = df[[
    "MathSupport",
    "EnglishSupport",
    "AttendanceSupport"
]]

readable_prediction = np.where(prediction == 1, "Yes", "No")

print(readable_prediction)
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
model =  model = OneVsRestClassifier(
    LogisticRegression(max_iter=1000)
)
model.fit(X_train,y_train)
y_predict = model.predict(X_test)
print(y_predict)

print(X)
print(y)
new_student = pd.DataFrame({
    "Attendance": [3],
    "MathScore": [70],
    "EnglishScore": [65],
    "QuizScore": [80],
    "MissedClasses": [2]
})

prediction = model.predict(new_student)

print(prediction)

[['Yes' 'Yes' 'No']]
[[1 1 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
    Attendance  MathScore  EnglishScore  QuizScore  MissedClasses
0           72         55            58         61              1
1           91         86            84         88              0
2           68         48            52         55              4
3           94         92            89         91              0
4           75         60            57         63              2
5           88         78            81         85              1
6           62         42            45         49              5
7           82         70            68         72              2
8           70         50            54         58              3
9           96         94            92         95              0
10          79         65            63         67              2
11          65         45            48         51              5
12          85         73            71         76              1
13          92    