In [14]:
import numpy as np

In [15]:
numbers = np.array([1,2,3,4,5])
results = numbers*10
results[(results>30)&(results<50)]

array([40])

In [16]:
price = np.array([100,200,300])
quantity = np.array([3,4,6])
price*quantity

array([ 300,  800, 1800])

In [17]:
#REsHAPEING
arr = np.array([1,2,3,4,5,6])
arr.reshape(2,3)
arr.reshape([-1])

array([1, 2, 3, 4, 5, 6])

In [18]:
age = np.array([20,40,50])

print(age)
type(age)

[20 40 50]


numpy.ndarray

In [19]:
import pandas as pd

In [22]:
df = pd.read_csv("Datasets/dataset.csv")
df

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
0,1,Gita,MERN Stack,Kathmandu,17,Female,2026-02-24,10000,10,Pending,73.0,46,98,5,Samriddha,9839323411,user0@gmail.com,Ongoing
1,2,Nabin,Data Science,Itahari,29,Female,2026-06-29,10000,20,Pending,68.0,31,63,3,Manish,9874340113,user1@gmail.com,Completed
2,3,Gita,MERN Stack,Dharan,20,Female,2026-02-20,5000,20,Paid,71.0,31,99,5,Samriddha,9874168652,user2@gmail.com,Completed
3,4,Gita,Digital Marketing,Itahari,20,Female,2026-05-23,7000,0,Pending,88.0,43,38,5,Manish,9864252889,user3@gmail.com,Ongoing
4,5,Gita,Data Science,Itahari,19,Male,2026-05-28,5000,0,Pending,100.0,89,98,5,Ishan,9864166467,user4@gmail.com,Ongoing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,346,Hari,UI/UX,Dharan,21,Female,2026-06-17,10000,20,Paid,98.0,87,56,5,Samriddha,9873827203,user345@gmail.com,Ongoing
346,347,Anisha,Digital Marketing,Biratnagar,31,Female,2026-03-21,5000,10,Paid,45.0,51,44,3,Samriddha,9864328504,user346@gmail.com,Ongoing
347,348,Sita,Flutter,Biratnagar,19,Male,2026-02-05,5000,20,Paid,80.0,89,39,5,Samriddha,9821459197,user347@gmail.com,Completed
348,349,Anisha,UI/UX,Itahari,27,Male,2026-05-05,5000,10,Paid,63.0,58,52,5,Ishan,9862269669,user348@gmail.com,Completed


In [32]:
array = np.array(df["course_fee"])
weights = np.array([10])
prediction = np.dot(array,weights)
prediction

ValueError: shapes (350,) and (1,) not aligned: 350 (dim 0) != 1 (dim 0)

In [29]:
type(array)

numpy.ndarray